import { Catalog, type CatalogManifest } from "@icad/core";

/**
 * Loads the real IBM icon catalog generated by `packages/catalog-build`
 * (docs/04-icon-catalog.md, roadmap M2) from the sibling `packages/catalog`
 * workspace package. Assets are bundled eagerly; if the catalog grows large
 * enough for this to matter, switch to lazy `import.meta.glob` imports.
 */
const manifestModules = import.meta.glob(
  "../../../packages/catalog/2.0.0/index.json",
  {
    eager: true,
    import: "default",
  },
);
const manifest = Object.values(manifestModules)[0] as CatalogManifest;

const assetModules = import.meta.glob(
  "../../../packages/catalog/2.0.0/icons/**/*.svg",
  {
    eager: true,
    query: "?raw",
    import: "default",
  },
) as Record<string, string>;

// Catalog assets on disk are full, standalone SVGs (viewBox 0 0 24 24); `Catalog`
// expects inner fragments (see packages/core/src/catalog/catalog.ts), so strip the
// outer <svg> tag here at load time.
function stripSvgWrapper(svg: string): string {
  return svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
}

export function createIbmCloudCatalog(): Catalog {
  const assets = new Map<string, string>();
  for (const [filePath, raw] of Object.entries(assetModules)) {
    const assetPath = filePath.match(/icons\/.+$/)?.[0];
    if (assetPath) assets.set(assetPath, stripSvgWrapper(raw));
  }
  return new Catalog(manifest, assets);
}
