import { Catalog, type CatalogManifest } from "@icad/core";

/**
 * Loads the real IBM icon catalog generated by `packages/catalog-build`
 * (docs/04-icon-catalog.md, roadmap M2/M13) from the sibling `packages/catalog`
 * workspace package. Assets are bundled eagerly; if the catalog grows large
 * enough for this to matter, switch to lazy `import.meta.glob` imports.
 *
 * The version to load isn't hardcoded here — `packages/catalog/current.json`
 * is the single source of truth a catalog re-pin flips (docs/04-icon-catalog.md
 * "Versioning strategy"), and the glob patterns below wildcard the version
 * segment so multiple version directories can coexist on disk (e.g. while
 * diffing an old vs. a newly generated one) without this loader caring.
 */
const currentVersionModules = import.meta.glob(
  "../../../packages/catalog/current.json",
  {
    eager: true,
    import: "default",
  },
);
const { version: currentVersion } = Object.values(currentVersionModules)[0] as {
  version: string;
};

const manifestModules = import.meta.glob(
  "../../../packages/catalog/*/index.json",
  {
    eager: true,
    import: "default",
  },
) as Record<string, CatalogManifest>;
const manifestEntry = Object.entries(manifestModules).find(([filePath]) =>
  filePath.includes(`/catalog/${currentVersion}/`),
);
if (!manifestEntry) {
  throw new Error(
    `packages/catalog/current.json points at version "${currentVersion}", but no ` +
      `packages/catalog/${currentVersion}/index.json was found.`,
  );
}
const manifest = manifestEntry[1];

const assetModules = import.meta.glob(
  "../../../packages/catalog/*/icons/**/*.svg",
  {
    eager: true,
    query: "?raw",
    import: "default",
  },
) as Record<string, string>;

// Catalog assets on disk are full, standalone SVGs (viewBox 0 0 24 24); `Catalog`
// expects inner fragments (see packages/core/src/catalog/catalog.ts), so strip the
// outer <svg> tag here at load time.
function stripSvgWrapper(svg: string): string {
  return svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
}

export function createIbmCloudCatalog(): Catalog {
  const assets = new Map<string, string>();
  for (const [filePath, raw] of Object.entries(assetModules)) {
    if (!filePath.includes(`/catalog/${currentVersion}/`)) continue;
    const assetPath = filePath.match(/icons\/.+$/)?.[0];
    if (assetPath) assets.set(assetPath, stripSvgWrapper(raw));
  }
  return new Catalog(manifest, assets);
}
